name: tp0
services:
  server:
    container_name: central
    image: server:latest
    entrypoint: python3 /main.py
    volumes:
      - ./server/config.ini:/config.ini
      - ./bets.csv:/bets.csv
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net

  client1:
    container_name: agencia1
    image: client:latest
    entrypoint: /client
    volumes:
      - ./client/config.yaml:/config.yaml
    environment:
      - CLI_ID=AGENCIA1
      - CLI_BET_FIRSTNAME='Santiago Lionel'
      - CLI_BET_LASTNAME='Lorca'
      - CLI_BET_DOCUMENT=30904465
      - CLI_BET_BIRTHDATE=1999-03-17
      - CLI_BET_NUMBER=7574
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
