name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    volumes:
      - ./server/config.ini:/config.ini
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    volumes:
      - ./client/config.yaml:/config.yaml
    environment:
      - CLI_ID=1
      - CLI_BET_FIRSTNAME=Client1
      - CLI_BET_LASTNAME=Lastname1
      - CLI_BET_DOCUMENT=10000001
      - CLI_BET_BIRTHDATE=1990-01-01
      - CLI_BET_NUMBER=7001
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
